// Guided starting points. Every story opens the Blink Lab on real SPHEREx
// frames; visit counts quoted in the text come from the pointing index.

export const STORIES = [
  {
    id: 'pluto',
    kicker: 'The original Planet X',
    title: 'Catch Pluto moving',
    body: 'Pluto',
    mode: 'fixed',
    view: 'trails',
    size: 196,
    accent: 'var(--survey-3)',
    blurb: 'In 1930 Clyde Tombaugh found Pluto by blinking photographs taken days apart. SPHEREx caught Pluto in 40 pointings. Here the stars are held still across 19 frames from autumn 2025, and Pluto crawls about 5 arcminutes between them.',
    tip: 'In Trails, still stars stay white and Pluto leaves a rainbow of dots, one per date. Switch to Blink and press play to watch it hop.',
  },
  {
    id: 'neptune',
    kicker: 'Found by mathematics',
    title: 'Neptune, the predicted planet',
    body: 'Neptune',
    mode: 'fixed',
    view: 'blink',
    autoplay: true,
    size: 196,
    accent: 'var(--survey-1)',
    blurb: 'Neptune was found in 1846 because Uranus drifted from its predicted path: the first successful "Planet X" hunt. SPHEREx saw it in 55 pointings across three all-sky surveys; within one survey it slides several arcminutes past the stars.',
    tip: 'Choose "Track object" to flip the view: Neptune holds still and the stars stream past instead.',
  },
  {
    id: 'uranus',
    kicker: 'An ice giant drifting',
    title: 'Uranus on the move',
    body: 'Uranus',
    mode: 'fixed',
    view: 'trails',
    size: 196,
    accent: 'var(--accent)',
    blurb: 'Uranus was the first planet discovered with a telescope, in 1781. In August 2025 SPHEREx imaged it 21 times over 19 days while it moved about 7 arcminutes across the sky.',
    tip: 'Uranus is bright enough to saturate the detector, so it glows with a halo. Watch the halo move against the fixed stars.',
  },
  {
    id: 'barnard',
    kicker: 'A star on the run',
    title: "Barnard's Star",
    target: 'barnard',
    size: 48,
    view: 'compare',
    accent: 'var(--danger)',
    blurb: 'The fastest-moving star in our sky shifts 10.4 arcseconds a year, almost two SPHEREx pixels between the first and last frames. Rings mark where it should be on each date.',
    tip: 'Compare the first and last frames with Swipe or Difference: a dark/bright pair means the star moved.',
  },
  {
    id: 'luhman16',
    kicker: 'Brown dwarfs',
    title: 'The nearest brown dwarfs',
    target: 'luhman16',
    size: 64,
    accent: 'var(--accent-2)',
    blurb: 'Luhman 16 is a pair of "failed stars" 6.5 light-years away. They are faint in visible light but glow in the infrared, and they move 2.8 arcseconds a year.',
    tip: 'Look at the wavelength of each frame: they are much brighter beyond 1 micron than at 0.8 microns.',
  },
  {
    id: 'nep',
    kicker: 'Deep field',
    title: 'The spot SPHEREx never stops watching',
    target: 'nep',
    size: 112,
    autoplay: true,
    accent: 'var(--ok)',
    blurb: 'Near the north ecliptic pole every SPHEREx orbit overlaps, so this patch was imaged in 3,920 pointings. Stacks of frames here reveal faint variable and transient sources.',
    tip: 'Pick one survey pass in the timeline to blink frames taken hours apart.',
  },
  {
    id: 'orion',
    kicker: 'Infrared beauty',
    title: 'Inside the Orion Nebula',
    target: 'orion',
    size: 196,
    autoplay: true,
    accent: 'var(--accent)',
    blurb: 'Near-infrared light slips through dust, revealing young stars inside the nebula. Each frame is taken at a different wavelength, so the nebula changes color and brightness from frame to frame.',
    tip: 'Switch the colormap to Infrared and raise the contrast.',
  },
];

export function storyById(id) {
  return STORIES.find((s) => s.id === id);
}
